### ISSUE TITLE
python 3.4 exceptions when concatenating bytes to str

### ISSUE THREAD

**Issue by cgiacomi** [coleifer/beefish#4]
Hi I am trying to use beefish with python 3.4 and I get the following error (which I don't get with python 2.7):

```
  File "/Users/cgia/sources/git/backup/backup/utils.py", line 42, in encrypt
     encrypt_file(file, '/secrets.enc', 'p@ssword')
  File "/Users/cgia/sources/git/backup/env/lib/python3.4/site-packages/beefish.py", line 92, in encrypt_file
     encrypt(in_fh, out_fh, key, chunk_size)
  File "/Users/cgia/sources/git/backup/env/lib/python3.4/site-packages/beefish.py", line 62, in encrypt
     buffer += _gen_padding(bytes_read, cipher.block_size)
  File "/Users/cgia/sources/git/backup/env/lib/python3.4/site-packages/beefish.py", line 37, in _gen_padding
    return padding + chr(bflag)
  TypeError: can't concat bytes to str
```

I was looking at the source and beefish.py line 37:

```
return padding + chr(bflag)
```

The python 3.4 documentation for chr() states:
https://docs.python.org/3.4/library/functions.html#chr

```
chr(i) - Returns the string representing a character whose Unicode code point is the integer i.
```

While the documentation for 2.7 states:
https://docs.python.org/2.7/library/functions.html#chr

```
chr(i) - Return a string of one character whose ASCII code is the integer i.
```

I attempted to add an str.decode() to line 37, to convert the string to bytes and this seems to work but then I run into other exceptions when trying to decode the file, so I decided I might ask you for help.

to test the differences I used virtualenv with 2.7 and pyvenv with 3.4, with 2.7 the code works perfectly.

thanks

**Comment by coleifer** [comment]
I think this is fixed.

**Comment by coleifer** [comment]
cc008c26856c7a50436866d5d273de42e4e5ee3d and 52ee07044c98aa27237ce4493e0d91a1ad240d1f
